# Generated by Django 5.2.13 on 2026-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interface', '0002_alter_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='modal_call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
