# Generated by Django 5.2.13 on 2026-05-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interface', '0003_chatmessage_modal_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
