# Generated by Django 5.2.13 on 2026-06-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interface', '0004_chatmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='mesh_upload',
            field=models.FileField(blank=True, null=True, upload_to='chat_meshes/'),
        ),
    ]
