# Generated by Django 5.2.13 on 2026-06-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_interface', '0005_chatmessage_mesh_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='object_paths',
            field=models.TextField(blank=True, default=''),
        ),
    ]
